apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog  
        image: natha1week08.azurecr.io/book_catalog:v1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_ow76_user:vwwUBNha0tNMZFtr29fKO0S5A22ThQ1b@dpg-crr1ki56l47c73cbid6g-a.oregon-postgres.render.com/week08_ow76"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management  
        image: natha1week08.azurecr.io/inventory_management:v1
        ports:
        - containerPort: 8002
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          value: "postgresql://week08_ow76_user:vwwUBNha0tNMZFtr29fKO0S5A22ThQ1b@dpg-crr1ki56l47c73cbid6g-a.oregon-postgres.render.com/week08_ow76"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002